from fstream import *

class Editor(Fstream):
    def __init__(self, parent=None) -> None:
        # super().__init__(parent)
        pass
    
    def display_edit(self):
        self.Monitor.clearContents()
        self.Monitor.setRowCount(1)
        self.DB_Read(data.table_index)
        
        col_count = 0
        _translate = QCoreApplication.translate
        for i in range(0,len(data.visible)):
            item = self.Monitor.horizontalHeaderItem(col_count)
            item.setText(_translate("MainWindow", data.header[i]))
            col_count += 1
        
        if data.table_empty:
            self.Monitor.removeRow(0)
            return
        row_count = 0
        col_count = 0
        for lines in data.content:
            for i in range(0,len(data.visible)):
                newItem = QtWidgets.QTableWidgetItem(str(lines[i]))
                newItem.setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)
                self.Monitor.setItem(row_count,col_count,newItem)
                col_count += 1
            row_count += 1
            col_count = 0
            if row_count==self.Monitor.rowCount():
                self.Monitor.insertRow(row_count)
        self.Monitor.removeRow(row_count)
    
    
    def data_Imp(self):
        self.DB_Import()
        self.DB_Load()
        self.freshTableList()
        self.display_edit()
        
        
    def opt_Exp(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(260, 105)
        Widget.setWindowTitle("导出表格")
        font = QFont()
        font.setPointSize(15)
        self.ExpTableWidget = QtWidgets.QWidget(Widget)
        self.input_exp_text = QtWidgets.QLabel(self.ExpTableWidget)
        self.input_exp_text.setGeometry(QRect(10, 10, 100, 40))
        self.input_exp_text.setFont(font)
        self.input_exp_text.setText("表格名称：")
        self.input_exp_edit = QtWidgets.QComboBox(self.ExpTableWidget)
        self.input_exp_edit.setGeometry(QRect(100, 10, 150, 40))
        self.input_exp_edit.setFont(font)
        self.input_exp_edit.addItem("all")
        self.input_exp_edit.addItems(data.table_list)
        self.input_exp_edit.setCurrentIndex(0)
        self.input_exp_done = QtWidgets.QPushButton(self.ExpTableWidget)
        self.input_exp_done.setGeometry(QRect(20, 55, 220, 40))
        self.input_exp_done.setFont(font)
        self.input_exp_done.setText("确认导出表格")
        self.input_exp_done.clicked.connect(self.data_Exp)
        self.input_exp_done.clicked.connect(Widget.close)
        Widget.exec_()
        
    def data_Exp(self):
        index = self.input_exp_edit.currentIndex() -1
        self.DB_Export(index)
        
        
    def opt_New(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(260, 105)
        Widget.setWindowTitle("创建新表格")
        font = QFont()
        font.setPointSize(15)
        self.NewTableWidget = QtWidgets.QWidget(Widget)
        self.input_new_text = QtWidgets.QLabel(self.NewTableWidget)
        self.input_new_text.setGeometry(QRect(10, 10, 100, 40))
        self.input_new_text.setFont(font)
        self.input_new_text.setText("表格名称：")
        self.input_new_edit = QtWidgets.QLineEdit(self.NewTableWidget)
        self.input_new_edit.setAlignment(Qt.AlignRight)
        self.input_new_edit.setGeometry(QRect(100, 10, 150, 40))
        self.input_new_edit.setFont(font)
        self.input_new_edit.setText("表格"+str(len(data.table_list)+1))
        self.input_new_done = QtWidgets.QPushButton(self.NewTableWidget)
        self.input_new_done.setGeometry(QRect(20, 55, 220, 40))
        self.input_new_done.setFont(font)
        self.input_new_done.setText("创建新表格")
        self.input_new_done.clicked.connect(self.data_New)
        self.input_new_done.clicked.connect(Widget.close)
        Widget.exec_()
        
    def data_New(self):
        table_name = self.input_new_edit.text()
        self.DB_NewTable(table_name)
        self.DB_Load()
        self.freshTableList()
        self.display_edit()
        
    
    def opt_Drp(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(260, 105)
        Widget.setWindowTitle("删除表格")
        font = QFont()
        font.setPointSize(15)
        self.DrpTableWidget = QtWidgets.QWidget(Widget)
        self.input_drp_text = QtWidgets.QLabel(self.DrpTableWidget)
        self.input_drp_text.setGeometry(QRect(10, 10, 100, 40))
        self.input_drp_text.setFont(font)
        self.input_drp_text.setText("表格名称：")
        self.input_drp_edit = QtWidgets.QComboBox(self.DrpTableWidget)
        self.input_drp_edit.setGeometry(QRect(100, 10, 150, 40))
        self.input_drp_edit.setFont(font)
        self.input_drp_edit.addItems(data.table_list)
        self.input_drp_edit.setCurrentIndex(data.table_index)
        self.input_drp_done = QtWidgets.QPushButton(self.DrpTableWidget)
        self.input_drp_done.setGeometry(QRect(20, 55, 220, 40))
        self.input_drp_done.setFont(font)
        self.input_drp_done.setText("确认删除表格")
        self.input_drp_done.clicked.connect(self.data_Drp)
        self.input_drp_done.clicked.connect(Widget.close)
        Widget.exec_()
        
    def data_Drp(self):
        index = self.input_drp_edit.currentIndex()
        self.DB_DropTable(index)
        self.DB_Load()
        self.freshTableList()
        self.display_edit()
    
    
    def opt_Add(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(480, 420)
        Widget.setWindowTitle("新增数据项")
        font = QFont()
        font.setPointSize(15)
        self.AddItemWidget = QtWidgets.QWidget(Widget)
        self.input_company_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_company_text.setGeometry(QRect(10, 10, 60, 40))
        self.input_company_text.setFont(font)
        self.input_company_text.setText("企业")
        self.input_company_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_company_edit.setGeometry(QRect(70, 10, 150, 40))
        self.input_company_edit.setFont(font)
        self.input_company_edit.setText("")
        self.input_id_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_id_text.setGeometry(QRect(250, 10, 60, 40))
        self.input_id_text.setFont(font)
        self.input_id_text.setText("型号")
        self.input_id_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_id_edit.setGeometry(QRect(310, 10, 150, 40))
        self.input_id_edit.setFont(font)
        self.input_id_edit.setText("")
        self.input_type_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_type_text.setGeometry(QRect(10, 60, 60, 40))
        self.input_type_text.setFont(font)
        self.input_type_text.setText("类型")
        self.input_type_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_type_edit.setGeometry(QRect(70, 60, 150, 40))
        self.input_type_edit.setFont(font)
        self.input_type_edit.setText("同步磁阻电机")
        self.input_size_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_size_text.setGeometry(QRect(250, 60, 60, 40))
        self.input_size_text.setFont(font)
        self.input_size_text.setText("机座号")
        self.input_size_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_size_edit.setGeometry(QRect(310, 60, 150, 40))
        self.input_size_edit.setFont(font)
        self.input_size_edit.setText("")
        self.input_power_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_power_text.setGeometry(QRect(10, 110, 60, 40))
        self.input_power_text.setFont(font)
        self.input_power_text.setText("功率")
        self.input_power_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_power_edit.setGeometry(QRect(70, 110, 150, 40))
        self.input_power_edit.setFont(font)
        self.input_power_edit.setText("0")
        self.input_voltage_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_voltage_text.setGeometry(QRect(250, 110, 60, 40))
        self.input_voltage_text.setFont(font)
        self.input_voltage_text.setText("电压")
        self.input_voltage_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_voltage_edit.setGeometry(QRect(310, 110, 150, 40))
        self.input_voltage_edit.setFont(font)
        self.input_voltage_edit.setText("0")
        self.input_current_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_current_text.setGeometry(QRect(10, 160, 60, 40))
        self.input_current_text.setFont(font)
        self.input_current_text.setText("电流")
        self.input_current_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_current_edit.setGeometry(QRect(70, 160, 150, 40))
        self.input_current_edit.setFont(font)
        self.input_current_edit.setText("0")
        self.input_speed_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_speed_text.setGeometry(QRect(250, 160, 60, 40))
        self.input_speed_text.setFont(font)
        self.input_speed_text.setText("转速")
        self.input_speed_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_speed_edit.setGeometry(QRect(310, 160, 150, 40))
        self.input_speed_edit.setFont(font)
        self.input_speed_edit.setText("0")
        self.input_efficiency_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_efficiency_text.setGeometry(QRect(10, 210, 60, 40))
        self.input_efficiency_text.setFont(font)
        self.input_efficiency_text.setText("效率")
        self.input_efficiency_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_efficiency_edit.setGeometry(QRect(70, 210, 150, 40))
        self.input_efficiency_edit.setFont(font)
        self.input_efficiency_edit.setText("0")
        self.input_powerfactor_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_powerfactor_text.setGeometry(QRect(250, 210, 60, 40))
        self.input_powerfactor_text.setFont(font)
        self.input_powerfactor_text.setText("功率\n因数")
        self.input_powerfactor_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_powerfactor_edit.setGeometry(QRect(310, 210, 150, 40))
        self.input_powerfactor_edit.setFont(font)
        self.input_powerfactor_edit.setText("0")
        self.input_frequency_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_frequency_text.setGeometry(QRect(10, 260, 60, 40))
        self.input_frequency_text.setFont(font)
        self.input_frequency_text.setText("频率")
        self.input_frequency_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_frequency_edit.setGeometry(QRect(70, 260, 150, 40))
        self.input_frequency_edit.setFont(font)
        self.input_frequency_edit.setText("0")
        self.input_torque_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_torque_text.setGeometry(QRect(250, 260, 60, 40))
        self.input_torque_text.setFont(font)
        self.input_torque_text.setText("转矩")
        self.input_torque_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_torque_edit.setGeometry(QRect(310, 260, 150, 40))
        self.input_torque_edit.setFont(font)
        self.input_torque_edit.setText("0")
        self.input_mass_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_mass_text.setGeometry(QRect(10, 310, 60, 40))
        self.input_mass_text.setFont(font)
        self.input_mass_text.setText("重量")
        self.input_mass_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_mass_edit.setGeometry(QRect(70, 310, 150, 40))
        self.input_mass_edit.setFont(font)
        self.input_mass_edit.setText("None")
        self.input_pole_text = QtWidgets.QLabel(self.AddItemWidget)
        self.input_pole_text.setGeometry(QRect(250, 310, 60, 40))
        self.input_pole_text.setFont(font)
        self.input_pole_text.setText("极数")
        self.input_pole_edit = QtWidgets.QLineEdit(self.AddItemWidget)
        self.input_pole_edit.setGeometry(QRect(310, 310, 150, 40))
        self.input_pole_edit.setFont(font)
        self.input_pole_edit.setText("None")
        self.input_add_done = QtWidgets.QPushButton(self.AddItemWidget)
        self.input_add_done.setGeometry(QRect(90, 360, 300, 40))
        self.input_add_done.setFont(font)
        self.input_add_done.setText("确认新增数据项")
        self.input_add_done.clicked.connect(self.data_Add)
        self.input_add_done.clicked.connect(Widget.close)
        Widget.exec_()
    
    def data_Add(self):
        cargo = []
        cargo.append(self.input_company_edit.text())
        cargo.append(self.input_id_edit.text())
        cargo.append(self.input_type_edit.text())
        cargo.append(self.input_size_edit.text())
        cargo.append(float(self.input_power_edit.text()))
        cargo.append(float(self.input_voltage_edit.text()))
        cargo.append(float(self.input_current_edit.text()))
        cargo.append(self.input_speed_edit.text())
        cargo.append(float(self.input_efficiency_edit.text()))
        cargo.append(float(self.input_powerfactor_edit.text()))
        cargo.append(self.input_frequency_edit.text())
        cargo.append(float(self.input_torque_edit.text()))
        cargo.append(self.input_mass_edit.text())
        cargo.append(self.input_pole_edit.text())
        self.DB_AddItem(cargo)
        self.DB_Load()
        self.display_edit()
        
            
    def opt_Del(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(260, 105)
        Widget.setWindowTitle("删除数据项")
        font = QFont()
        font.setPointSize(15)
        self.DelItemWidget = QtWidgets.QWidget(Widget)
        self.input_del_text = QtWidgets.QLabel(self.DelItemWidget)
        self.input_del_text.setGeometry(QRect(10, 10, 100, 40))
        self.input_del_text.setFont(font)
        self.input_del_text.setText("项序号：")
        self.input_del_edit = QtWidgets.QSpinBox(self.DelItemWidget)
        self.input_del_edit.setAlignment(Qt.AlignRight)
        self.input_del_edit.setGeometry(QRect(100, 10, 150, 40))
        self.input_del_edit.setFont(font)
        self.input_del_edit.setMinimum(0)
        self.input_del_edit.setMaximum(data.table_len[data.table_index])
        self.input_del_edit.setProperty("value", 0)
        self.input_del_done = QtWidgets.QPushButton(self.DelItemWidget)
        self.input_del_done.setGeometry(QRect(20, 55, 220, 40))
        self.input_del_done.setFont(font)
        self.input_del_done.setText("确认删除数据项")
        self.input_del_done.clicked.connect(self.data_Del)
        self.input_del_done.clicked.connect(Widget.close)
        Widget.exec_()
    
    def data_Del(self):
        index = int(self.input_del_edit.text())
        self.DB_DelItem(index)
        self.DB_Load()
        self.display_edit()
        
    def opt_Mod(self):
        Widget = QtWidgets.QDialog(self)
        Widget.resize(480, 480)
        Widget.setWindowTitle("修订数据项")
        font = QFont()
        font.setPointSize(15)
        self.ModItemWidget = QtWidgets.QWidget(Widget)
        self.input_mod_text = QtWidgets.QLabel(self.ModItemWidget)
        self.input_mod_text.setGeometry(QRect(30, 10, 100, 40))
        self.input_mod_text.setFont(font)
        self.input_mod_text.setText("项序号：")
        self.input_mod_edit = QtWidgets.QSpinBox(self.ModItemWidget)
        self.input_mod_edit.setAlignment(Qt.AlignRight)
        self.input_mod_edit.setGeometry(QRect(140, 10, 150, 40))
        self.input_mod_edit.setFont(font)
        self.input_mod_edit.setMinimum(0)
        self.input_mod_edit.setMaximum(data.table_len[data.table_index])
        self.input_mod_edit.setProperty("value", 0)
        self.input_mod_done = QtWidgets.QPushButton(self.ModItemWidget)
        self.input_mod_done.setGeometry(QRect(300, 10, 150, 40))
        self.input_mod_done.setFont(font)
        self.input_mod_done.setText("查询项")
        self.input_mod_done.clicked.connect(self.data_Seh)
        self.mod_company_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_company_text.setGeometry(QRect(10, 70, 60, 40))
        self.mod_company_text.setFont(font)
        self.mod_company_text.setText("企业")
        self.mod_company_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_company_edit.setGeometry(QRect(70, 70, 150, 40))
        self.mod_company_edit.setFont(font)
        self.mod_company_edit.setText("")
        self.mod_id_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_id_text.setGeometry(QRect(250, 70, 60, 40))
        self.mod_id_text.setFont(font)
        self.mod_id_text.setText("型号")
        self.mod_id_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_id_edit.setGeometry(QRect(310, 70, 150, 40))
        self.mod_id_edit.setFont(font)
        self.mod_id_edit.setText("")
        self.mod_type_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_type_text.setGeometry(QRect(10, 120, 60, 40))
        self.mod_type_text.setFont(font)
        self.mod_type_text.setText("类型")
        self.mod_type_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_type_edit.setGeometry(QRect(70, 120, 150, 40))
        self.mod_type_edit.setFont(font)
        self.mod_type_edit.setText("同步磁阻电机")
        self.mod_size_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_size_text.setGeometry(QRect(250, 120, 60, 40))
        self.mod_size_text.setFont(font)
        self.mod_size_text.setText("机座号")
        self.mod_size_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_size_edit.setGeometry(QRect(310, 120, 150, 40))
        self.mod_size_edit.setFont(font)
        self.mod_size_edit.setText("")
        self.mod_power_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_power_text.setGeometry(QRect(10, 170, 60, 40))
        self.mod_power_text.setFont(font)
        self.mod_power_text.setText("功率")
        self.mod_power_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_power_edit.setGeometry(QRect(70, 170, 150, 40))
        self.mod_power_edit.setFont(font)
        self.mod_power_edit.setText("0")
        self.mod_voltage_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_voltage_text.setGeometry(QRect(250, 170, 60, 40))
        self.mod_voltage_text.setFont(font)
        self.mod_voltage_text.setText("电压")
        self.mod_voltage_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_voltage_edit.setGeometry(QRect(310, 170, 150, 40))
        self.mod_voltage_edit.setFont(font)
        self.mod_voltage_edit.setText("0")
        self.mod_current_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_current_text.setGeometry(QRect(10, 220, 60, 40))
        self.mod_current_text.setFont(font)
        self.mod_current_text.setText("电流")
        self.mod_current_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_current_edit.setGeometry(QRect(70, 220, 150, 40))
        self.mod_current_edit.setFont(font)
        self.mod_current_edit.setText("0")
        self.mod_speed_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_speed_text.setGeometry(QRect(250, 220, 60, 40))
        self.mod_speed_text.setFont(font)
        self.mod_speed_text.setText("转速")
        self.mod_speed_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_speed_edit.setGeometry(QRect(310, 220, 150, 40))
        self.mod_speed_edit.setFont(font)
        self.mod_speed_edit.setText("0")
        self.mod_efficiency_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_efficiency_text.setGeometry(QRect(10, 270, 60, 40))
        self.mod_efficiency_text.setFont(font)
        self.mod_efficiency_text.setText("效率")
        self.mod_efficiency_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_efficiency_edit.setGeometry(QRect(70, 270, 150, 40))
        self.mod_efficiency_edit.setFont(font)
        self.mod_efficiency_edit.setText("0")
        self.mod_powerfactor_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_powerfactor_text.setGeometry(QRect(250, 270, 60, 40))
        self.mod_powerfactor_text.setFont(font)
        self.mod_powerfactor_text.setText("功率\n因数")
        self.mod_powerfactor_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_powerfactor_edit.setGeometry(QRect(310, 270, 150, 40))
        self.mod_powerfactor_edit.setFont(font)
        self.mod_powerfactor_edit.setText("0")
        self.mod_frequency_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_frequency_text.setGeometry(QRect(10, 320, 60, 40))
        self.mod_frequency_text.setFont(font)
        self.mod_frequency_text.setText("频率")
        self.mod_frequency_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_frequency_edit.setGeometry(QRect(70, 320, 150, 40))
        self.mod_frequency_edit.setFont(font)
        self.mod_frequency_edit.setText("0")
        self.mod_torque_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_torque_text.setGeometry(QRect(250, 320, 60, 40))
        self.mod_torque_text.setFont(font)
        self.mod_torque_text.setText("转矩")
        self.mod_torque_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_torque_edit.setGeometry(QRect(310, 320, 150, 40))
        self.mod_torque_edit.setFont(font)
        self.mod_torque_edit.setText("0")
        self.mod_mass_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_mass_text.setGeometry(QRect(10, 370, 60, 40))
        self.mod_mass_text.setFont(font)
        self.mod_mass_text.setText("重量")
        self.mod_mass_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_mass_edit.setGeometry(QRect(70, 370, 150, 40))
        self.mod_mass_edit.setFont(font)
        self.mod_mass_edit.setText("None")
        self.mod_pole_text = QtWidgets.QLabel(self.ModItemWidget)
        self.mod_pole_text.setGeometry(QRect(250, 370, 60, 40))
        self.mod_pole_text.setFont(font)
        self.mod_pole_text.setText("极数")
        self.mod_pole_edit = QtWidgets.QLineEdit(self.ModItemWidget)
        self.mod_pole_edit.setGeometry(QRect(310, 370, 150, 40))
        self.mod_pole_edit.setFont(font)
        self.mod_pole_edit.setText("None")
        self.mod_add_done = QtWidgets.QPushButton(self.ModItemWidget)
        self.mod_add_done.setGeometry(QRect(90, 420, 300, 40))
        self.mod_add_done.setFont(font)
        self.mod_add_done.setText("确认修订数据项")
        self.mod_add_done.clicked.connect(self.data_Mod)
        self.mod_add_done.clicked.connect(Widget.close)
        Widget.exec_()
    
    def data_Seh(self):
        index = int(self.input_mod_edit.text())
        self.DB_SearchItem(index)
        self.mod_company_edit.setText(str(data.content[0][1]))
        self.mod_id_edit.setText(str(data.content[0][2]))
        self.mod_type_edit.setText(str(data.content[0][3]))
        self.mod_size_edit.setText(str(data.content[0][4]))
        self.mod_power_edit.setText(str(data.content[0][5]))
        self.mod_voltage_edit.setText(str(data.content[0][6]))
        self.mod_current_edit.setText(str(data.content[0][7]))
        self.mod_speed_edit.setText(str(data.content[0][8]))
        self.mod_efficiency_edit.setText(str(data.content[0][9]))
        self.mod_powerfactor_edit.setText(str(data.content[0][10]))
        self.mod_frequency_edit.setText(str(data.content[0][11]))
        self.mod_torque_edit.setText(str(data.content[0][12]))
        self.mod_mass_edit.setText(str(data.content[0][13]))
        self.mod_pole_edit.setText(str(data.content[0][14]))
    
    def data_Mod(self):
        cargo = []
        cargo.append(self.mod_company_edit.text())
        cargo.append(self.mod_id_edit.text())
        cargo.append(self.mod_type_edit.text())
        cargo.append(self.mod_size_edit.text())
        cargo.append(float(self.mod_power_edit.text()))
        cargo.append(float(self.mod_voltage_edit.text()))
        cargo.append(float(self.mod_current_edit.text()))
        cargo.append(self.mod_speed_edit.text())
        cargo.append(float(self.mod_efficiency_edit.text()))
        cargo.append(float(self.mod_powerfactor_edit.text()))
        cargo.append(self.mod_frequency_edit.text())
        cargo.append(float(self.mod_torque_edit.text()))
        cargo.append(self.mod_mass_edit.text())
        cargo.append(self.mod_pole_edit.text())
        cargo.append(int(self.input_mod_edit.text()))
        self.DB_ModifyItem(cargo)
        self.DB_Load()
        self.display_edit()
    
    
    def init_Editor(self):
        pass
        
    def signals_Editor(self):
        self.pushButton_imp.clicked.connect(self.data_Imp)
        self.pushButton_exp.clicked.connect(self.opt_Exp)
        self.pushButton_new.clicked.connect(self.opt_New)
        self.pushButton_drp.clicked.connect(self.opt_Drp)
        self.pushButton_add.clicked.connect(self.opt_Add)
        self.pushButton_del.clicked.connect(self.opt_Del)
        self.pushButton_mod.clicked.connect(self.opt_Mod)
        
        